
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-Tides-Controller","number":33,"title":"Ray - Add Controller and Test for Tides","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-2/pull/33"},{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-ZipCode-Controller","number":32,"title":"kw - added controller and test for zipcode","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-2/pull/32"}]
