
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"Richard-PublicHoliday","number":31,"title":"Added Public Holiday Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-Location-Controller","number":30,"title":"Add Location Service and Controller + Location Query Bugfix","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-2/pull/30"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-HomeController","number":23,"title":"Customize Home Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-2/pull/23"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-Joke-Controller","number":21,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-2/pull/21"}]
