
name: Create Issues for team01
on:
  workflow_dispatch:
jobs:
  createIssues:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Customize Home Controller and Tests
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Customize Home Controller and Tests
          body: |
            ## Acceptance criteria
            
            - [ ] The Home Controller is updated with the names of the team members.
            - [ ] The Home Controller Tests are updated with the names of the team members.

            ## Details
            
            See: <https://ucsb-cs156.github.io/m23/lab/team01/>, step 3.2
          
      - name: Adjust links in README.md
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Customize Home Controller and Tests
          body: |
            ## Acceptance criteria
            
            - [ ] The README.md file is updated with links as specified in the instructions.
            
            ## Details
            
            See the README.md file in the repo for details.
        
